services:
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=true  # Activez la sécurité
        - xpack.security.authc.api_key.enabled=true
        - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}  # Lecture depuis le .env
        - PORT=9200  # Définir le port d'écoute pour render
        - network.host=0.0.0.0  # Écouter sur toutes les interfaces
      networks:
        - mon_reseau
      ports:
        - "9200:9200"  # Expose le port 9200 pour l'accès à Elasticsearch
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200/"]
        interval: 30s
        timeout: 10s
        retries: 5
  fastapi:
    depends_on:
      - elasticsearch 
    build: .
    networks:
      - mon_reseau
    ports:
      - "8000:8000"
    env_file:
      - .env
networks:
  mon_reseau:
    driver: bridge