# Dockerfile.elasticsearch
FROM docker.elastic.co/elasticsearch/elasticsearch:8.9.0

ENV discovery.type=single-node
ENV xpack.security.enabled=true
ENV xpack.security.authc.api_key.enabled=true
ENV ELASTIC_PASSWORD=${ELASTIC_PASSWORD} 

# Script pour attendre que Elasticsearch démarre puis créer une API Key
COPY ./create-api-key.sh /create-api-key.sh

# Exécuter Elasticsearch puis générer l'API Key
#CMD ["/create-api-key.sh"]